import Footer from "@/component/Footer";
import Navbar from "@/component/Navbar";
import "./globals.css";
export const metadata = {
  title: "SunCart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      
    >
      <body>
        <Navbar />
        {children}
        <Footer />
        </body>
    </html>
  );
}
